# Generated by Django 3.1.5 on 2021-01-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('approved', 'approved'), ('rejected', 'rejected')], default='waiting', max_length=200, verbose_name='Request status')),
            ],
            options={
                'verbose_name': 'Register request ',
                'verbose_name_plural': 'Register requests ',
            },
        ),
    ]
