# Generated by Django 3.1.5 on 2021-01-19 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterRequestState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(choices=[('approved', 'Approved'), ('rejected_by_employee', 'Rejected by Employee'), ('rejected', 'Rejected'), ('pending_employee_review', 'Pending Employee Review'), ('pending_leader_review', 'Pending Leader Review')], max_length=200)),
                ('note', models.TextField(blank=True, null=True)),
                ('RegisterRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='train.registerrequest')),
            ],
            options={
                'verbose_name': 'Register request state',
                'verbose_name_plural': 'Register requests state',
            },
        ),
        migrations.CreateModel(
            name='RegisterRequestApproved',
            fields=[
            ],
            options={
                'verbose_name': 'Register request approved',
                'verbose_name_plural': 'Register requests approved',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('handle.registerrequeststate',),
        ),
        migrations.CreateModel(
            name='RegisterRequestPendingEmployeeReview',
            fields=[
            ],
            options={
                'verbose_name': 'Register request Pending employee review',
                'verbose_name_plural': 'Register requests Pending employee review',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('handle.registerrequeststate',),
        ),
        migrations.CreateModel(
            name='RegisterRequestPendingLeaderReview',
            fields=[
            ],
            options={
                'verbose_name': 'Register request Pending Leader review',
                'verbose_name_plural': 'Register requests Pending Leader review',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('handle.registerrequeststate',),
        ),
        migrations.CreateModel(
            name='RegisterRequestRejected',
            fields=[
            ],
            options={
                'verbose_name': 'Register request rejected',
                'verbose_name_plural': 'Register requests rejected',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('handle.registerrequeststate',),
        ),
        migrations.CreateModel(
            name='RegisterRequestRejectedBYEmployee',
            fields=[
            ],
            options={
                'verbose_name': 'Register request rejected',
                'verbose_name_plural': 'Register requests rejected',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('handle.registerrequeststate',),
        ),
    ]
